"""Record the endocytosis / lysosomal cholesterol-mTORC1 synthesis in scinv-6808f3d27a90 (2026-09-24)."""
import json, os, subprocess, sys
CORE=os.path.expanduser('~/.claude/plugins/cache/skillful-alhazen/alhazen-core/0.1.0')
S='/home/afrost/.claude/external-skills/alhazen-skill-deep-research/skills/scientific-literature/scientific_literature.py'
INV='scinv-6808f3d27a90'
def run(*a):
    p=subprocess.run(['uv','run','--project',CORE,'--with','requests','python',S,*a],capture_output=True,text=True,
                     env={**os.environ,'TYPEDB_DATABASE':'alh_deep_research'},timeout=300)
    o=p.stdout
    try: return json.loads(o[o.index('{'):])
    except Exception: print('FAIL',a[0],o[-300:],p.stderr[-300:]); return {}
CLAIMS=[
("primary",
 "THE ENDOCYTIC ROUTE THAT TAKES UP APOE-LIPOPROTEIN IS NOT SPECIFICALLY CHANGED IN APOE4 VS APOE2 CARRIERS. Six downloaded GO steps (lipoprotein receptors GO:0030228, clathrin-dependent endocytosis/coated pit GO:0072583+GO:0005905, early endosome GO:0005769, recycling endosome GO:0055037, late endosome and endosome-to-lysosome GO:0005770+GO:0008333, lysosome GO:0005764) were scored with the SE-decile-matched M-score in 50 LC and ERC cells, and ranked by |M| against 60 real GO pathways, after removing any reference pathway that holds more than 25 percent of the step's genes and after removing the APOE cis window (APOE, APOC2). Median percentiles were 25th to 49th; the only local exception was the lysosome in ERC Visium (85th). The receptors are individually flat in LC (LDLR FDR >= 0.48, LRP1 >= 0.07, SORL1 >= 0.60). The secretory arm ranks slightly higher but is still inside the real-pathway range (ER 57th, Golgi 64th, exocytosis 68th).",
 "computational",0.8,
 "Uses the estimand of mito/null_test.py unchanged, so it is directly comparable with the mitochondrial null (37th percentile) already recorded. Being typical against real pathways is not the same as no change: most real pathways shift a little in this contrast, and the umbrella endocytosis set has a signed median M of +1.2. But nothing about the uptake route is unusual, so an 'APOE4 impairs endocytosis' transcriptional story is not supported by these data. The ERC Visium lysosome signal is one of four datasets and should be treated as a lead, not a finding. Build: ~/apoe-research/endocytosis/01_build_data.py; figure: https://claude.ai/artifact/KCN5GQaEECrJk8Xap4AdNh."),
("primary",
 "THE LYSOSOMAL CHOLESTEROL-TO-mTORC1 SENSING APPARATUS IS TRANSCRIPTIONALLY FLAT IN APOE4 VS APOE2 CARRIERS, INCLUDING THE NEWLY DESCRIBED CHOLESTEROL SENSOR TM6SF1. Across 24 genes spanning uptake, hydrolysis, egress, contact-site transfer, sensing and output (LDLR, LRP1, LIPA, NPC2, NPC1, STARD3, OSBPL1A, VAPA, OSBP, SLC38A9, TM6SF1, LAMTOR1, LAMTOR2, RRAGA, RRAGC, FLCN, RHEB, MTOR, RPTOR, TFEB, ABCA1, SYT7, ARL8B), none reaches FDR < 0.05 in any of the five LC domains. The closest are LRP1 (min FDR 0.073), NPC2 (0.092) and ABCA1 (0.13). TM6SF1 ranges from -0.158 to +0.069 log2FC with min FDR 0.71. SLC38A9 is not in the LC universe. In the ERC carrier tables only two single-cluster hits clear 0.05: NPC2 -1.05 in the small WM.uf domain (FDR 0.033) and TFEB -1.16 in vascular spots (FDR 0.029).",
 "computational",0.75,
 "This agrees with, and extends to the sensing machinery, the retraction scsynth-b87f99e1eb14 (no 5-prime-TOP stabilisation, so no transcriptional sign of raised mTORC1) and the well-powered lysosomal/cathepsin null scsynth-6b8f6df14f18. The limit must travel with the claim: mTORC1 is regulated by recruitment, nucleotide state and cholesterol binding, not by abundance of its parts, so flat transcripts do not exclude a signalling change. They exclude only a compensatory transcriptional response of the apparatus. The two ERC hits are isolated, in low-gene-count or vascular clusters, and ERC is underpowered (0.1 to 0.3 percent of genes clear 0.05), so neither should be interpreted."),
("secondary",
 "LITERATURE SYNTHESIS, A MECHANISTIC BRIDGE: apoE-lipoprotein endocytosis feeds lysosomal cholesterol into three converging mTORC1 sensors, so APOE isoform effects on particle uptake have a defined route to lysosomal growth signalling and TFEB. Receptor-mediated uptake delivers cholesteryl esters to the lysosome, where LIPA hydrolyses them and NPC2 hands free cholesterol to NPC1 (Infante 2008, PNAS). Lysosomal cholesterol then activates mTORC1 through three sensors: (1) an SLC38A9-NPC1 signalling complex (Castellano 2017, Science); (2) OSBP-mediated ER-to-lysosome transfer at VAP-tethered contact sites (Lim 2019, Nat Cell Biol); and (3) TM6SF1, a lysosomal homodimer whose TM1-6 pocket binds cholesterol and which engages LAMTOR1 of Ragulator in a cholesterol-dependent way. Loss of TM6SF1 lowers S6K1 and 4E-BP1 phosphorylation and constitutively activates TFEB (Hong, Jia, Wang, Elghobashi-Meinhardt, Hobbs, Li, PNAS 2026, doi 10.1073/pnas.2622424123). All three act on the Ragulator-Rag platform (Sancak 2010) together with the v-ATPase (Zoncu 2011) and FLCN-FNIP, the RagC/D GAP (Tsun 2013). Cholesterol also leaves late endosomes by STARD3 and ORP1L at VAP contacts (Wilhelm 2017; Rocha 2009).",
 "review",0.6,
 "This is why the figure now draws TM6SF1 against Ragulator and ER tubules at NPC1 contact sites. The testable APOE prediction combines this route with scsynth-5b7dba3aa6c8, in which R136S reverses APOE3's microglial cholesterol flux (less uptake, more efflux). If lysosomal cholesterol is the input, R136S, and plausibly APOE2 with its weak LDLR/LRP1 binding (scilit-paper-250d968ed0cb), should lower lysosomal cholesterol, weaken TM6SF1-LAMTOR1 engagement and mTORC1 activity, and raise nuclear TFEB. APOE4 should do the opposite only if its uptake or lysosomal cholesterol load is higher. Our transcript data cannot test this, because the apparatus is flat by construction of the question. The test needs microglial or astrocytic lysosomal cholesterol (filipin or LysoTracker co-stain), pS6K/p4E-BP1 and TFEB localisation, across isoform-matched iPSC glia. TM6SF1 is a Hobbs-lab protein with a lipid-genetics pedigree (its paralog TM6SF2 lipidates APOB lipoproteins), which makes it an attractive, unstudied APOE-adjacent candidate. Confidence is held at 0.6 because the bridge is assembled across papers, none of which varies APOE."),
]
ids=[]
for typ,stmt,etype,conf,arg in CLAIMS:
    r=run('add-synthesized-claim','--investigation',INV,'--type',typ,'--statement',stmt)
    cid=r.get('synthesized_claim_id')
    if not cid: print('!! no id',r); continue
    e=run('add-evidence','--claim-id',cid,'--argument',arg,'--confidence',str(conf),'--evidence-type',etype)
    print(typ,cid,'evidence',e.get('evidence_id')); ids.append(cid)
json.dump(ids,open('/home/afrost/apoe-research/endocytosis/kb_claims.json','w'))
